export const DEFAULTS = {
  people: [
    { id: 1, name: 'Me',      color: 'blue'   },
    { id: 2, name: 'Partner', color: 'purple' },
  ],
  // savingsAccounts replaces the single currentSavings number
  savingsAccounts: [
    { id: 1, name: 'Checking Account', amount: 5000,  active: true, assignedTo: null },
    { id: 2, name: 'Savings Account',  amount: 10000, active: true, assignedTo: null },
  ],
  furloughDate: '2026-02-21',
  unemployment: {
    startDate: '2026-03-07',
    weeklyAmount: 450,
    durationWeeks: 26,
    assignedTo: null,
  },
  expenses: [
    { id: 1, category: 'Rent / Mortgage',    monthlyAmount: 1500, essential: true,  assignedTo: null },
    { id: 2, category: 'Food & Groceries',   monthlyAmount: 400,  essential: true,  assignedTo: null },
    { id: 3, category: 'Utilities',          monthlyAmount: 150,  essential: true,  assignedTo: null },
    { id: 4, category: 'Health / Insurance', monthlyAmount: 250,  essential: true,  assignedTo: null },
    { id: 5, category: 'Transportation',     monthlyAmount: 200,  essential: false, assignedTo: null },
    { id: 6, category: 'Subscriptions',      monthlyAmount: 80,   essential: false, assignedTo: null },
    { id: 7, category: 'Misc / Personal',    monthlyAmount: 120,  essential: false, assignedTo: null },
  ],
  whatIf: {
    expenseReductionPct: 0,
    expenseRaisePct: 0,
    sideIncomeMonthly: 0,
    emergencyFloor: 0,
    benefitDelayWeeks: 0,
    benefitCutWeeks: 0,
    freezeDate: '',
    jobOfferSalary: 0,
    jobOfferStartDate: '',
    freelanceRamp: [],
    partnerIncomeMonthly: 0,
    partnerStartDate: '',
  },
  oneTimeExpenses: [],
  oneTimePurchases: [],
  oneTimeIncome: [],
  monthlyIncome: [],
  jobs: [],
  assets: [],
  investments: [],
  subscriptions: [
    { id: 101, name: 'Netflix',  monthlyAmount: 17,  active: true, assignedTo: null },
    { id: 102, name: 'Spotify',  monthlyAmount: 11,  active: true, assignedTo: null },
    { id: 103, name: 'Internet', monthlyAmount: 60,  active: true, assignedTo: null },
  ],
  creditCards: [],
  notificationPreferences: {
    enabled: true,
    thresholds: {
      runwayCritical: 3,
      runwayWarning: 6,
      runwaySafe: 12,
      benefitEndDays: 30,
      balanceMilestones: [0.5, 0.25, 0.10],
    },
    dismissedIds: [],
    mutedUntil: null,
  },
  plaidMeta: {},
  jobScenarios: [],
  retirement: {
    currentAge: 30,
    targetRetirementAge: 65,
    currentBalance: 0,
    monthlyContribution: 500,
    annualReturnPct: 7,
    inflationPct: 3,
    targetMode: 'nestEgg',
    targetNestEgg: 1000000,
    desiredAnnualIncome: 40000,
    withdrawalRatePct: 4,
    assignedTo: null,
  },
}
