/**
 * State Unemployment Insurance Benefits Data (2025-2026)
 *
 * Sources:
 *   - U.S. DOL Employment & Training Administration (oui.doleta.gov)
 *   - Bench Accounting state-by-state analysis (bench.co)
 *   - Saving to Invest 2026 benefits table (savingtoinvest.com)
 *   - Individual state DOL / workforce agency websites
 *   - CBPP unemployment weeks analysis (cbpp.org)
 *   - SingleMotherGuide state benefits table (singlemotherguide.com)
 *
 * Last updated: March 2026
 *
 * Notes:
 *   - maxWeeklyBenefit is the base individual amount (without dependents)
 *     unless otherwise noted. Some states provide higher amounts with
 *     dependent allowances; these are noted in calculationMethod.
 *   - maxWeeks reflects the CURRENT effective duration based on each
 *     state's unemployment rate as of early 2026. States with variable
 *     durations include a maxWeeksRange and notes in the description.
 *   - waitingPeriod: { weeks: 0 } means no unpaid waiting week.
 *   - filingUrl points to the state's primary online UI claims portal.
 */

export const STATE_UNEMPLOYMENT_DATA = [
  {
    stateCode: 'AL',
    stateName: 'Alabama',
    maxWeeklyBenefit: 275,
    maxWeeks: 14,
    maxWeeksRange: '14-20',
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1/26 of average of two highest base-period quarters',
    filingUrl: 'https://labor.alabama.gov/unemploymentcompensation',
  },
  {
    stateCode: 'AK',
    stateName: 'Alaska',
    maxWeeklyBenefit: 370,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: 'Benefits chart based on total wages in base period; ~90% of weekly wage for low earners, declining percentage for higher earners',
    filingUrl: 'https://labor.alaska.gov/unemployment/',
  },
  {
    stateCode: 'AZ',
    stateName: 'Arizona',
    maxWeeklyBenefit: 320,
    maxWeeks: 24,
    maxWeeksRange: '24-26',
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1/25 of earnings in highest quarter of base period',
    filingUrl: 'https://des.az.gov/services/employment/unemployment-individual',
  },
  {
    stateCode: 'AR',
    stateName: 'Arkansas',
    maxWeeklyBenefit: 451,
    maxWeeks: 20,
    maxWeeksRange: '12-20',
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1/26 of average earnings over four base-period quarters',
    filingUrl: 'https://ezarc.adws.arkansas.gov/',
  },
  {
    stateCode: 'CA',
    stateName: 'California',
    maxWeeklyBenefit: 450,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: 'Sliding scale chart based on highest quarter earnings; approximately 60-70% of weekly wages for lower earners',
    filingUrl: 'https://edd.ca.gov/unemployment/',
  },
  {
    stateCode: 'CO',
    stateName: 'Colorado',
    maxWeeklyBenefit: 844,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: 'Higher of: 60% of avg weekly wage over two highest quarters, or 50% of avg weekly wage over last 12 months',
    filingUrl: 'https://cdle.colorado.gov/unemployment',
  },
  {
    stateCode: 'CT',
    stateName: 'Connecticut',
    maxWeeklyBenefit: 721,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 0, description: 'No waiting period' },
    calculationMethod: '1/26 of average earnings in two highest base-period quarters; plus $15/dependent (max 5)',
    filingUrl: 'https://portal.ct.gov/dol/unemployment-benefits',
  },
  {
    stateCode: 'DE',
    stateName: 'Delaware',
    maxWeeklyBenefit: 450,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 0, description: 'No waiting period' },
    calculationMethod: '1/46 of total wages in two highest base-period quarters',
    filingUrl: 'https://labor.delaware.gov/divisions/unemployment-insurance/',
  },
  {
    stateCode: 'DC',
    stateName: 'District of Columbia',
    maxWeeklyBenefit: 444,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1/26 of earnings in highest quarter of base period',
    filingUrl: 'https://does.dc.gov/service/unemployment-compensation-process',
  },
  {
    stateCode: 'FL',
    stateName: 'Florida',
    maxWeeklyBenefit: 275,
    maxWeeks: 12,
    maxWeeksRange: '12-23',
    waitingPeriod: { weeks: 0, description: 'No waiting period' },
    calculationMethod: '1/26 of earnings in highest quarter of base period',
    filingUrl: 'https://www.floridajobs.org/Reemployment-Assistance-Service-Center/reemployment-assistance/claimants',
  },
  {
    stateCode: 'GA',
    stateName: 'Georgia',
    maxWeeklyBenefit: 365,
    maxWeeks: 14,
    maxWeeksRange: '14-26',
    waitingPeriod: { weeks: 0, description: 'No waiting period' },
    calculationMethod: '1/42 of earnings in two highest quarters, or 1/21 of highest quarter (whichever is higher)',
    filingUrl: 'https://dol.georgia.gov/get-unemployment-assistance',
  },
  {
    stateCode: 'HI',
    stateName: 'Hawaii',
    maxWeeklyBenefit: 871,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1/21 of earnings in highest quarter of base period',
    filingUrl: 'https://labor.hawaii.gov/ui/',
  },
  {
    stateCode: 'ID',
    stateName: 'Idaho',
    maxWeeklyBenefit: 590,
    maxWeeks: 21,
    maxWeeksRange: '10-26',
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1/26 of earnings in highest quarter of base period',
    filingUrl: 'https://www.labor.idaho.gov/unemployment-benefits/',
  },
  {
    stateCode: 'IL',
    stateName: 'Illinois',
    maxWeeklyBenefit: 628,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '47% of avg weekly earnings in two highest quarters; +$178 with non-working spouse, +$199 with dependent child',
    filingUrl: 'https://ides.illinois.gov/',
  },
  {
    stateCode: 'IN',
    stateName: 'Indiana',
    maxWeeklyBenefit: 390,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '47% of avg weekly earnings in base period (may be lower based on wage distribution)',
    filingUrl: 'https://www.in.gov/dwd/indiana-unemployment/',
  },
  {
    stateCode: 'IA',
    stateName: 'Iowa',
    maxWeeklyBenefit: 763,
    maxWeeks: 16,
    maxWeeksRange: '16-26',
    waitingPeriod: { weeks: 0, description: 'No waiting period' },
    calculationMethod: '1/23 of earnings in highest quarter; higher with dependents (up to 4)',
    filingUrl: 'https://workforce.iowa.gov/unemployment',
  },
  {
    stateCode: 'KS',
    stateName: 'Kansas',
    maxWeeklyBenefit: 637,
    maxWeeks: 16,
    maxWeeksRange: '16-26',
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '4.25% of earnings in highest quarter of base period',
    filingUrl: 'https://www.dol.ks.gov/unemployment',
  },
  {
    stateCode: 'KY',
    stateName: 'Kentucky',
    maxWeeklyBenefit: 665,
    maxWeeks: 16,
    maxWeeksRange: '12-24',
    waitingPeriod: { weeks: 1, description: 'One-week waiting period; may be paid back after specified unemployment period' },
    calculationMethod: '1.1923% of total base-period earnings',
    filingUrl: 'https://kewes.ky.gov/',
  },
  {
    stateCode: 'LA',
    stateName: 'Louisiana',
    maxWeeklyBenefit: 275,
    maxWeeks: 12,
    maxWeeksRange: '12-20',
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1/25 of avg earnings over four base-period quarters, multiplied by 1.2075',
    filingUrl: 'https://www.laworks.net/',
  },
  {
    stateCode: 'ME',
    stateName: 'Maine',
    maxWeeklyBenefit: 623,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1/22 of average earnings in two highest base-period quarters; plus $25 per dependent',
    filingUrl: 'https://www.maine.gov/unemployment/claimants/',
  },
  {
    stateCode: 'MD',
    stateName: 'Maryland',
    maxWeeklyBenefit: 430,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 0, description: 'No waiting period' },
    calculationMethod: '1/24 of earnings in highest quarter; plus $8 per dependent (max 5)',
    filingUrl: 'https://beacon.labor.maryland.gov/',
  },
  {
    stateCode: 'MA',
    stateName: 'Massachusetts',
    maxWeeklyBenefit: 1105,
    maxWeeks: 30,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '50% of avg weekly wage; plus $25 per dependent child (up to 50% of WBA); 30 weeks when metro area unemployment exceeds 5.1%',
    filingUrl: 'https://www.mass.gov/unemployment-insurance-ui-for-workers',
  },
  {
    stateCode: 'MI',
    stateName: 'Michigan',
    maxWeeklyBenefit: 530,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 0, description: 'No waiting period' },
    calculationMethod: '4.1% of earnings in highest quarter of base period',
    filingUrl: 'https://www.michigan.gov/leo/bureaus-agencies/uia',
  },
  {
    stateCode: 'MN',
    stateName: 'Minnesota',
    maxWeeklyBenefit: 948,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: 'Higher of: 50% of (1/13 of highest quarter earnings), or 50% of (1/52 of total base-period earnings)',
    filingUrl: 'https://www.uimn.org/',
  },
  {
    stateCode: 'MS',
    stateName: 'Mississippi',
    maxWeeklyBenefit: 235,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1/26 of earnings in highest quarter of base period',
    filingUrl: 'https://mdes.ms.gov/unemployment-claims/',
  },
  {
    stateCode: 'MO',
    stateName: 'Missouri',
    maxWeeklyBenefit: 320,
    maxWeeks: 8,
    maxWeeksRange: '8-20',
    waitingPeriod: { weeks: 1, description: 'One-week waiting period; may be reimbursed after qualifying period' },
    calculationMethod: '1/25 of avg earnings in two highest base-period quarters',
    filingUrl: 'https://labor.mo.gov/unemployed-workers',
  },
  {
    stateCode: 'MT',
    stateName: 'Montana',
    maxWeeklyBenefit: 767,
    maxWeeks: 24,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: 'Higher of: 1% of total base-period earnings, or 1.9% of earnings in two highest base-period quarters',
    filingUrl: 'https://uid.dli.mt.gov/',
  },
  {
    stateCode: 'NE',
    stateName: 'Nebraska',
    maxWeeklyBenefit: 564,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '50% of avg weekly wage during base period',
    filingUrl: 'https://dol.nebraska.gov/UIBenefits',
  },
  {
    stateCode: 'NV',
    stateName: 'Nevada',
    maxWeeklyBenefit: 631,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 0, description: 'No waiting period' },
    calculationMethod: '1/25 of earnings in highest quarter of base period',
    filingUrl: 'https://ui.nv.gov/css.html',
  },
  {
    stateCode: 'NH',
    stateName: 'New Hampshire',
    maxWeeklyBenefit: 427,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1% to 1.1% of annual base-period earnings',
    filingUrl: 'https://www.nhes.nh.gov/services/claimants/',
  },
  {
    stateCode: 'NJ',
    stateName: 'New Jersey',
    maxWeeklyBenefit: 905,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 0, description: 'No waiting period' },
    calculationMethod: '60% of avg weekly wage during base year',
    filingUrl: 'https://myunemployment.nj.gov/',
  },
  {
    stateCode: 'NM',
    stateName: 'New Mexico',
    maxWeeklyBenefit: 598,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '53.5% of avg weekly wages in highest quarter of base period',
    filingUrl: 'https://www.dws.state.nm.us/',
  },
  {
    stateCode: 'NY',
    stateName: 'New York',
    maxWeeklyBenefit: 869,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period (effective claims after 6/28/2021)' },
    calculationMethod: '1/25 to 1/26 of earnings in highest quarter of base period',
    filingUrl: 'https://dol.ny.gov/unemployment/file-your-first-claim',
  },
  {
    stateCode: 'NC',
    stateName: 'North Carolina',
    maxWeeklyBenefit: 350,
    maxWeeks: 12,
    maxWeeksRange: '12-20',
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: 'Total earnings in last two completed quarters divided by 52',
    filingUrl: 'https://des.nc.gov/apply-unemployment',
  },
  {
    stateCode: 'ND',
    stateName: 'North Dakota',
    maxWeeklyBenefit: 815,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1/65 of total earnings in two highest quarters, plus 50% of third-highest quarter earnings',
    filingUrl: 'https://www.jobsnd.com/unemployment-individuals',
  },
  {
    stateCode: 'OH',
    stateName: 'Ohio',
    maxWeeklyBenefit: 757,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '50% of avg weekly wage from base period; higher with dependents (1-2+)',
    filingUrl: 'https://unemployment.ohio.gov/',
  },
  {
    stateCode: 'OK',
    stateName: 'Oklahoma',
    maxWeeklyBenefit: 649,
    maxWeeks: 16,
    maxWeeksRange: '16-26',
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1/23 of earnings in highest quarter of base period',
    filingUrl: 'https://oklahoma.gov/oesc/individuals/unemployment.html',
  },
  {
    stateCode: 'OR',
    stateName: 'Oregon',
    maxWeeklyBenefit: 872,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1.25% of total base-period earnings',
    filingUrl: 'https://unemployment.oregon.gov/',
  },
  {
    stateCode: 'PA',
    stateName: 'Pennsylvania',
    maxWeeklyBenefit: 605,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '(Highest quarter earnings x 4% + $2) x 0.98; or 50% of full-time weekly wage, whichever is higher',
    filingUrl: 'https://www.uc.pa.gov/',
  },
  {
    stateCode: 'RI',
    stateName: 'Rhode Island',
    maxWeeklyBenefit: 745,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '3.85% of average wages in two highest base-period quarters; plus $15/dependent or 5% of WBA (max 5 dependents)',
    filingUrl: 'https://dlt.ri.gov/individuals/unemployment-insurance',
  },
  {
    stateCode: 'SC',
    stateName: 'South Carolina',
    maxWeeklyBenefit: 350,
    maxWeeks: 20,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '50% of avg weekly wage in highest quarter of base period',
    filingUrl: 'https://dew.sc.gov/',
  },
  {
    stateCode: 'SD',
    stateName: 'South Dakota',
    maxWeeklyBenefit: 553,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1/26 of earnings in highest quarter of base period',
    filingUrl: 'https://dlr.sd.gov/ra/individuals/',
  },
  {
    stateCode: 'TN',
    stateName: 'Tennessee',
    maxWeeklyBenefit: 325,
    maxWeeks: 12,
    maxWeeksRange: '12-20',
    waitingPeriod: { weeks: 1, description: 'One-week waiting period; may be reimbursed if eligible for 4+ consecutive weeks' },
    calculationMethod: '1/26 of earnings in highest quarter of base period',
    filingUrl: 'https://www.tn.gov/workforce/unemployment.html',
  },
  {
    stateCode: 'TX',
    stateName: 'Texas',
    maxWeeklyBenefit: 605,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1/25 of earnings in highest quarter, capped at 47.6% of state avg weekly wage',
    filingUrl: 'https://www.twc.texas.gov/jobseekers/unemployment-benefits-services',
  },
  {
    stateCode: 'UT',
    stateName: 'Utah',
    maxWeeklyBenefit: 777,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1/26 of earnings in highest quarter of base period, minus $5',
    filingUrl: 'https://jobs.utah.gov/ui/home',
  },
  {
    stateCode: 'VT',
    stateName: 'Vermont',
    maxWeeklyBenefit: 757,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1/45 of total earnings in two highest base-period quarters',
    filingUrl: 'https://labor.vermont.gov/unemployment-insurance',
  },
  {
    stateCode: 'VA',
    stateName: 'Virginia',
    maxWeeklyBenefit: 378,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '1/26 of earnings in highest quarter of base period',
    filingUrl: 'https://www.vec.virginia.gov/unemployed',
  },
  {
    stateCode: 'WA',
    stateName: 'Washington',
    maxWeeklyBenefit: 1152,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '3.85% of average of two highest quarters in base year (sum of two highest quarters / 2 x 0.0385)',
    filingUrl: 'https://esd.wa.gov/unemployment',
  },
  {
    stateCode: 'WV',
    stateName: 'West Virginia',
    maxWeeklyBenefit: 662,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '55% of 1/52 of statewide median wages for your wage class',
    filingUrl: 'https://workforcewv.org/unemployment.html',
  },
  {
    stateCode: 'WI',
    stateName: 'Wisconsin',
    maxWeeklyBenefit: 370,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 1, description: 'One-week unpaid waiting period' },
    calculationMethod: '4% of earnings in highest quarter of base period (effectively 1/25)',
    filingUrl: 'https://dwd.wisconsin.gov/ui/',
  },
  {
    stateCode: 'WY',
    stateName: 'Wyoming',
    maxWeeklyBenefit: 624,
    maxWeeks: 26,
    maxWeeksRange: null,
    waitingPeriod: { weeks: 0, description: 'No waiting period' },
    calculationMethod: '4% of earnings in highest quarter of base period (effectively 1/25)',
    filingUrl: 'https://dws.wyo.gov/dws-division/unemployment-insurance/wyui/',
  },
]

/**
 * Utility: look up a single state by its two-letter code.
 * Returns undefined when the code is not found.
 */
export function getStateByCode(code) {
  if (!code) return undefined
  return STATE_UNEMPLOYMENT_DATA.find(
    (s) => s.stateCode === code.toUpperCase(),
  )
}

/**
 * Utility: return a { code: label } map suitable for <select> options.
 */
export function getStateOptions() {
  return STATE_UNEMPLOYMENT_DATA.map((s) => ({
    value: s.stateCode,
    label: `${s.stateName} (${s.stateCode})`,
  }))
}

/**
 * Utility: given a state code return the default unemployment config
 * that can be merged into the app's unemployment settings.
 */
export function getDefaultUnemploymentConfig(stateCode) {
  const state = getStateByCode(stateCode)
  if (!state) return null
  return {
    weeklyAmount: state.maxWeeklyBenefit,
    durationWeeks: state.maxWeeks,
    waitingWeeks: state.waitingPeriod.weeks,
    stateName: state.stateName,
    stateCode: state.stateCode,
  }
}
